- name: Create SAs and bindings
  hosts: localhost
  gather_facts: false
  vars:
    name_space: tools # use all for all namespaces
    verify_cert: false
    exclude_namespaces: [] # optional when name_space is all, skip these namespaces
    service_accounts:
      - { service_account: aap, state: present, role: cluster-admin, role_kind: ClusterRole, bind_scope: cluster, scc_context: anyuid, token: true }
      - { service_account: cli-tool, state: present, role: cluster-devel, role_kind: ClusterRole, bind_scope: cluster, scc_context: none, token: false }
  roles:
    - ado.openshift.service_accounts
